In [2]:
import os
print("Notebook working directory:", os.getcwd())

Notebook working directory: /Users/emmaphan/Documents/Comp Chem/Cl Transporter/script

In [3]:
import sys
import os

# Project root
project_root = "/Users/emmaphan/Documents/Comp Chem/Cl Transporter"
sys.path.append(os.path.join(project_root, "models"))
sys.path.append(project_root)

print("Paths added:", sys.path[-2:])

Paths added: ['/Users/emmaphan/Documents/Comp Chem/Cl Transporter/models', '/Users/emmaphan/Documents/Comp Chem/Cl Transporter']

In [4]:
import models.fm4m as fm4m
import pandas as pd
import numpy as np

import pyarrow as pa
import pyarrow.parquet as pq


from sklearn.svm import SVR
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

from rdkit import Chem
from rdkit.Chem.Descriptors import CalcMolDescriptors
from rdkit.Chem import MolFromSmiles

print ("okay")

okay

In [5]:
train_df = pd.read_csv("/Users/emmaphan/Documents/Comp Chem/Cl Transporter/data/training.csv")
test_df = pd.read_csv("/Users/emmaphan/Documents/Comp Chem/Cl Transporter/data/test.csv")

print (train_df.shape, test_df.shape)

(1348, 7) (175, 3)

In [6]:
#train_smiles = train_df["SMILES"].to_list()
test_smiles = test_df["SMILES"].to_list()
test_activity = test_df["Activity (1 = active, 0 = inactive)"].to_list()
len(test_smiles)
print (test_activity)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [7]:
#multiple undersampling

train_active = train_df[train_df['Activity (1 = active, 0 = inactive)'] == 1]
train_inactive = train_df[train_df['Activity (1 = active, 0 = inactive)'] == 0]

print(len(train_active))    # =54
print(len(train_inactive))  # =1294

inactive_shuffled = train_inactive.sample(frac=1, random_state=42)
inactive_chunks = np.array_split(inactive_shuffled, 19)
print([len(chunk) for chunk in inactive_chunks])

training_sets = []

for i, inactive_chunk in enumerate(inactive_chunks):
    subset = pd.concat(
        [train_active, inactive_chunk],
        ignore_index=True
    )
    training_sets.append(subset)

train_smiles = {}
train_activity = {} 

for i, col in enumerate(training_sets):
    train_smiles[i] = col["SMILES"].to_list()
    train_activity[i] = col["Activity (1 = active, 0 = inactive)"].to_list()

len(train_smiles[1])

54
1294
[69, 69, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68]

/opt/anaconda3/envs/smi-ted-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

123

In [8]:
print(train_activity[1])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [9]:
#SMILES to descriptor
from rdkit import Chem
from rdkit.Chem.Descriptors import CalcMolDescriptors
from rdkit.Chem import MolFromSmiles

def features(smiles):
      m = MolFromSmiles(smiles)
      vals = list(CalcMolDescriptors(m).values())
      return vals
    

train_rdkit = {}  # new dictionary

for i in train_smiles:
    rdkit_list = []  # temporary list for this key
    for mol in train_smiles[i]:
        rdkit_value = features(mol)  # translate each element
        rdkit_list.append(rdkit_value)  # add to the temp list
        train_rdkit[i] = rdkit_list  # assign the translated list to the new dict
    
test_rdkit = []
for smiles in test_smiles: 
    test_rdkit.append(features(smiles))

In [10]:
print (len(train_smiles[1]))
print (len(train_rdkit[1]))
len(train_activity[1])
#print (train_rdkit[1])

123
123

123

In [11]:
import sklearn
print(sklearn.__version__)

1.6.1

In [12]:
#RF
rf5 = RandomForestClassifier(n_estimators=5, max_depth = 10, random_state=42)
rf5.fit (train_rdkit[1],train_activity[1])
rf5_pred = rf5.predict(test_rdkit)
print("okay")

print (rf5_pred)
accuracy = accuracy_score(test_activity, rf5_pred)
print (accuracy)

okay
[0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1
 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 0 1]
0.8171428571428572

In [13]:
#try for 1 data set
#model_type = "SMI-TED"
#train_emb, test_emb = fm4m.get_representation(train_smiles[1],test_smiles, model_type, return_tensor=False)

#try on all data set
model_type = "SMI-TED"

train_emb = {}
test_emb = {}

for i in train_smiles:
    train_emb[i], test_emb[i] = fm4m.get_representation(
        train_smiles[i],
        test_smiles,
        model_type,
        return_tensor=True
    )

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding

/opt/anaconda3/envs/smi-ted-env/lib/python3.9/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.42s/it]
100%|█████████████████████████████████████████████| 1/1 [00:28<00:00, 28.50s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.90s/it]
100%|█████████████████████████████████████████████| 1/1 [00:29<00:00, 29.83s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.02s/it]
100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.64s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.18s/it]
100%|█████████████████████████████████████████████| 1/1 [00:30<00:00, 30.09s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.76s/it]
100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.32s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:32<00:00, 32.04s/it]
100%|█████████████████████████████████████████████| 1/1 [00:45<00:00, 45.43s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:22<00:00, 22.07s/it]
100%|█████████████████████████████████████████████| 1/1 [00:31<00:00, 31.06s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:22<00:00, 22.55s/it]
100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.85s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.25s/it]
100%|█████████████████████████████████████████████| 1/1 [00:30<00:00, 30.81s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.88s/it]
100%|█████████████████████████████████████████████| 1/1 [00:29<00:00, 29.87s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.41s/it]
100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.73s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:28<00:00, 28.83s/it]
100%|█████████████████████████████████████████████| 1/1 [00:28<00:00, 28.05s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.79s/it]
100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.23s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.12s/it]
100%|█████████████████████████████████████████████| 1/1 [00:32<00:00, 32.15s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.29s/it]
100%|█████████████████████████████████████████████| 1/1 [00:30<00:00, 30.52s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:33<00:00, 33.50s/it]
100%|█████████████████████████████████████████████| 1/1 [00:29<00:00, 29.40s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.71s/it]
100%|█████████████████████████████████████████████| 1/1 [00:32<00:00, 32.10s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:22<00:00, 22.73s/it]
100%|█████████████████████████████████████████████| 1/1 [00:28<00:00, 28.79s/it]

Random Seed: 12345
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Vocab size: 2393
[INFERENCE MODE - smi-ted-Light]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.16s/it]
100%|█████████████████████████████████████████████| 1/1 [00:32<00:00, 32.65s/it]

In [14]:
print(train_emb)

{0: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.5361, -0.5094,  0.0441,  ...,  0.7537,  0.5697, -0.1126],
        [ 0.4179, -0.5579,  0.0471,  ...,  0.9715,  0.6433, -0.2357],
        [ 0.3794, -0.5162,  0.0555,  ...,  0.8102,  0.5745, -0.1365]]), 1: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4093, -0.5356,  0.0826,  ...,  0.8513,  0.6102, -0.1370],
        [ 0.3401, -0.5559,  0.0515,  ...,  0.8256,  0.6066, -0.1034],
        [ 0.4252, -0.6105,  0.0780,  ...,  0.8691,  0.6292, -0.2355]]), 2: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3965, -0.4598,  0.0897,  ...,  0.7231,  0.6192, -0.0931],
        [ 0.3600, -0.4221,  0.0728,  ...,  0.8410,  0.6343, -0.0655],
        [ 0.3486, -0.5236,  0.0594,  ...,  0.8925,  0.6011, -0.0290]]), 3: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4032, -0.4584,  0.0791,  ...,  0.7972,  0.5306, -0.1785],
        [ 0.3842, -0.4424,  0.1199,  ...,  0.9266,  0.5706,  0.0038],
        [ 0.4514, -0.5500,  0.0760,  ...,  0.8430,  0.6131, -0.1490]]), 4: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3423, -0.5224,  0.1177,  ...,  0.9433,  0.6251, -0.0759],
        [ 0.3376, -0.5671,  0.0724,  ...,  0.8809,  0.6438, -0.1780],
        [ 0.3733, -0.4728,  0.0964,  ...,  0.8697,  0.6120, -0.1703]]), 5: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4521, -0.4919,  0.0873,  ...,  0.7727,  0.6132, -0.2510],
        [ 0.4656, -0.4691,  0.0793,  ...,  0.8159,  0.6947, -0.2227],
        [ 0.4470, -0.5675,  0.0574,  ...,  0.8714,  0.5812, -0.1555]]), 6: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4329, -0.5605,  0.0655,  ...,  0.8998,  0.6260, -0.1770],
        [ 0.4426, -0.5292,  0.1003,  ...,  0.8893,  0.6962, -0.1777],
        [ 0.4592, -0.5283,  0.0521,  ...,  0.8671,  0.6477, -0.0934]]), 7: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3895, -0.4730,  0.0840,  ...,  0.8235,  0.6114, -0.1975],
        [ 0.4291, -0.5449,  0.0725,  ...,  0.8874,  0.5926, -0.1525],
        [ 0.4585, -0.4583,  0.0708,  ...,  0.8160,  0.6250, -0.1294]]), 8: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3401, -0.5374,  0.0505,  ...,  0.8654,  0.6413, -0.1252],
        [ 0.4323, -0.5502,  0.1010,  ...,  0.8333,  0.5777, -0.1385],
        [ 0.4242, -0.4906,  0.0827,  ...,  0.8881,  0.6243, -0.0169]]), 9: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3440, -0.4666,  0.0757,  ...,  0.8768,  0.5642,  0.0190],
        [ 0.5431, -0.5251,  0.0959,  ...,  0.7715,  0.5826,  0.0111],
        [ 0.4106, -0.5640,  0.0846,  ...,  0.9445,  0.5985, -0.1488]]), 10: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.5046, -0.4560,  0.0819,  ...,  0.8354,  0.5819, -0.1364],
        [ 0.3673, -0.4752,  0.0120,  ...,  0.8857,  0.7450, -0.1851],
        [ 0.4458, -0.5581,  0.0769,  ...,  0.8952,  0.6196, -0.2050]]), 11: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4690, -0.5216,  0.0576,  ...,  0.9040,  0.5831, -0.0252],
        [ 0.4104, -0.5200,  0.1028,  ...,  0.8573,  0.6112, -0.1271],
        [ 0.3309, -0.4300,  0.0985,  ...,  0.8146,  0.5899, -0.2789]]), 12: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3704, -0.5368,  0.0675,  ...,  0.8742,  0.6166, -0.1042],
        [ 0.4250, -0.4194,  0.0420,  ...,  0.8338,  0.5286, -0.0285],
        [ 0.3663, -0.5374,  0.0335,  ...,  0.8007,  0.5400, -0.0297]]), 13: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3585, -0.5089,  0.0665,  ...,  0.7851,  0.5641, -0.0426],
        [ 0.3636, -0.5528,  0.0777,  ...,  0.8025,  0.5715, -0.1192],
        [ 0.3822, -0.5552,  0.0841,  ...,  0.8068,  0.5642, -0.0905]]), 14: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4999, -0.4282,  0.0746,  ...,  0.6169,  0.6266, -0.0680],
        [ 0.4060, -0.4731,  0.0755,  ...,  0.8016,  0.6192, -0.0105],
        [ 0.4434, -0.5354,  0.0775,  ...,  0.7943,  0.5936, -0.1746]]), 15: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3594, -0.4912,  0.1248,  ...,  0.9198,  0.6275, -0.1586],
        [ 0.3867, -0.4765,  0.0469,  ...,  0.8451,  0.6128, -0.2156],
        [ 0.3937, -0.4891,  0.0860,  ...,  1.0680,  0.5849, -0.2898]]), 16: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3319, -0.4854,  0.1034,  ...,  0.8367,  0.6332, -0.1698],
        [ 0.3646, -0.4047,  0.0655,  ...,  0.8079,  0.5942,  0.0404],
        [ 0.4189, -0.4507,  0.0802,  ...,  0.8800,  0.6355, -0.0907]]), 17: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.4140, -0.5496,  0.0986,  ...,  0.9186,  0.7055, -0.1875],
        [ 0.3657, -0.5321,  0.1191,  ...,  0.8299,  0.6077, -0.1571],
        [ 0.4721, -0.5320,  0.0586,  ...,  0.8579,  0.5857, -0.0830]]), 18: tensor([[ 0.3457, -0.4892,  0.1002,  ...,  0.8100,  0.6090, -0.0267],
        [ 0.4098, -0.4338,  0.0565,  ...,  0.8571,  0.6816, -0.1899],
        [ 0.4631, -0.5216,  0.0923,  ...,  0.8149,  0.6306, -0.1073],
        ...,
        [ 0.3250, -0.4008,  0.0930,  ...,  0.8814,  0.5475, -0.0144],
        [ 0.3435, -0.4898,  0.1061,  ...,  0.8290,  0.6043, -0.1876],
        [ 0.3847, -0.5437,  0.0916,  ...,  0.8904,  0.5933, -0.1017]])}

In [15]:
print(train_emb.shape)

AttributeError: 'dict' object has no attribute 'shape'

In [16]:
type(train_emb)

dict

In [17]:
train_emb[0:2]

TypeError: unhashable type: 'slice'

In [18]:
#RF
rf5 = RandomForestClassifier(n_estimators=15, max_depth = 10, random_state=42)
rf5.fit (train_rdkit[1],train_activity[1])
rf5_pred = rf5.predict(test_rdkit)
print("okay")

print (rf5_pred)
accuracyrf5 = accuracy_score(test_activity, rf5_pred)
print (accuracyrf5)

okay
[0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 0]
0.7771428571428571

In [19]:
rf5 = RandomForestClassifier(n_estimators=15, max_depth = 10, random_state=42)
smited=rf5.fit (train_emb[1],train_activity[1])
smited_pred = rf5.predict(test_emb[1])
print("okay")

print (smited_pred)
accuracy = accuracy_score(test_activity, smited_pred)
print (accuracy)

okay
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1]
0.8

In [20]:
#train_smiles[1]

In [21]:
print(len(train_smiles[1]))
print(len(list(train_emb[1])))
print(type(train_emb[1]))
print (len(train_activity[1]))
#all have 123 entries
len(list(train_emb[1]))

train_emb[1].shape

123
123
<class 'torch.Tensor'>
123

torch.Size([123, 768])

In [22]:
#rf5.fit (train_rdkit[1],train_activity[1])
#rf5_pred = rf5.predict(test_rdkit)
print(len(train_rdkit[1]))
print(len(train_activity[1]))
print(len(test_rdkit))

123
123
175

In [23]:
#create Parquet file
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

trainsmiles_col = train_smiles[1]
trainsmited_col = list(train_emb[1])
trainactivity_col = train_activity[1]

frame = {
    "Train SMILES": trainsmiles_col,
    "Train SMILES-TED": [t.detach().cpu().numpy() for t in trainsmited_col],#covert tensor to 
    "Activity": trainactivity_col
}
df = pd.DataFrame(frame)
#df.to_parquet("training_1.parquet", engine="pyarrow")
df

,Train SMILES,Train SMILES-TED,Activity
0,CC(CC(C#N)(C1=CC=CC=C1)C2=CC=CC=C2)N3CCCCC3,"[0.34571952, -0.4891502, 0.10022025, 0.3237361...",1
1,C1=CC(=CC=C1C2=NC3=C(N=C(N=C3N=C2C4=CC=C(C=C4)...,"[0.4098275, -0.4337771, 0.056540385, 0.3883391...",1
2,CCN(CC)CCN1C2=CC=CC=C2SC3=C1C4=CC=CC=C4C=C3,"[0.46312547, -0.5215707, 0.092277415, 0.384997...",1
3,CC(C)(C)NC(=S)NC(C)(C)C,"[0.30377987, -0.49192154, 0.12796305, 0.386750...",1
4,CC1=COC(CC1)(C)C=NCC(=C)C,"[0.42571047, -0.51897144, 0.092369385, 0.43873...",1
...,...,...,...
118,C1=CC=C(C=C1)C(=O)N2C(C=CC3=C2C=CC4=CC=CC=C43)C#N,"[0.35004827, -0.55080354, 0.06762384, 0.358878...",0
119,CC1=C(C=CC(=N1)C(=O)O)OC,"[0.36783245, -0.5063963, 0.08102232, 0.4008098...",0
120,CC(C)C(=O)C1=CC(=C(C=C1)O)O,"[0.40933627, -0.5356133, 0.082636885, 0.381247...",0
121,C1=CC=C(C=C1)C2=CC(=C(N2)C3=NC=CC4=CC=CC=C43)C#N,"[0.34010127, -0.5558511, 0.05154382, 0.3368733...",0
122,C1=CSC(=N1)NC(=O)C=CC(=O)O,"[0.4252454, -0.610497, 0.07798961, 0.433919, 0...",0

In [24]:
outputtrain = '/Users/emmaphan/Documents/Comp Chem/Cl Transporter/data/training_complete'

for i in range(18):
    trainsmiles_col = train_smiles[i]
    trainsmited_col = list(train_emb[i])
    trainactivity_col = train_activity[i]

    frame = {
        "Train SMILES": trainsmiles_col,
        "Train SMILES-TED": [t.detach().cpu().numpy() for t in trainsmited_col],
        "Activity": trainactivity_col
    }

    df = pd.DataFrame(frame)
    df.to_parquet(
        f"{outputtrain}/training_{i+1}.parquet",
        engine="pyarrow"
    )

In [25]:
print(len(test_smiles))
print(len((test_emb[1])))
print(type(test_emb[1]))
print (len(test_activity))
#all have 123 entries
len(list(train_emb[1]))

test_emb[1].shape
print (test_activity)

175
175
<class 'torch.Tensor'>
175
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [26]:
testsmiles_col = test_smiles
testsmited_col = list(test_emb[1])
testactivity_col = test_activity

frame = {
    "Test SMILES": testsmiles_col,
    "Test SMILES-TED": [t.detach().cpu().numpy() for t in testsmited_col],#covert tensor to 
    "Activity": testactivity_col 
}
df = pd.DataFrame(frame)
#df.to_parquet("training_1.parquet", engine="pyarrow")
df

,Test SMILES,Test SMILES-TED,Activity
0,CCOC(=O)NC1=CC2=C(C=C1)N=C(N2)C3=CSC=N3,"[0.43053472, -0.5042212, 0.021477599, 0.428175...",0
1,CSC1=NC(=C(S1)C(=O)NC2=CC=C(C=C2)[N+](=O)[O-])N,"[0.41468257, -0.5559679, 0.081442624, 0.382502...",0
2,CCCC(=O)N(C)C1=NC2=C(C=C(C=C2)Cl)C(=[N+](C1)[O...,"[0.44089022, -0.5182809, 0.10519825, 0.3779951...",0
3,CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)SC...,"[0.55152303, -0.4284187, 0.057089463, 0.394849...",0
4,CC1=NC2=C(C=CN2)C(=N1)NCC3=CC=CC=C3,"[0.3535877, -0.5111972, 0.07820781, 0.40937755...",0
...,...,...,...
170,OC1=C(C(NC2=CC(C(F)(F)F)=CC(C(F)(F)F)=C2)=O)C=...,"[0.40523592, -0.42657423, 0.1257377, 0.3822839...",1
171,O=C(/C=C/C(NC1CCCCC1)=O)NC2CCCCC2,"[0.41647348, -0.48067212, 0.09011023, 0.361469...",1
172,O=C(N(CCNC(C1=CC=C(Cl)C=C1)=O)C(N2CCNC(C3=CC=C...,"[0.43154377, -0.42166585, 0.079758115, 0.33677...",1
173,C1(N2CC(CN(CC3=CC=CC=C3)C4)CC4C2)=NC(N5CC6CC(C...,"[0.34182513, -0.4397151, 0.09460954, 0.3177235...",1
174,O=C(N[C@@H](C(C)C)C1=NC(C(NCCCCCC)=O)=C(C)N1C)...,"[0.4653018, -0.45722818, 0.033581614, 0.371725...",1

In [27]:
outputtest = '/Users/emmaphan/Documents/Comp Chem/Cl Transporter/data/test_complete'

for i in range(18):
    testsmiles_col = test_smiles
    testsmited_col = list(test_emb[1])
    testactivity_col = test_activity

    frame = {
    "Test SMILES": testsmiles_col,
    "Test SMILES-TED": [t.detach().cpu().numpy() for t in testsmited_col],#covert tensor to 
    "Activity": testactivity_col }

    df = pd.DataFrame(frame)
    df.to_parquet(
        f"{outputtest}/test_{i+1}.parquet",
        engine="pyarrow"
    )

In [28]:
#accuracysmited5 = []
for i in range (19): 
    rf5 = RandomForestClassifier(n_estimators=5, max_depth = 10, random_state=42)
    smited=rf5.fit (train_emb[i],train_activity[i])
    smited_pred = rf5.predict(test_emb[i])

    accuracy = accuracy_score(test_activity, smited_pred)
    #accuracysmited5.append(accuracy)
    print(i,accuracy)
    
#print(accuracysmited5)

0 0.7371428571428571
1 0.7714285714285715
2 0.72
3 0.76
4 0.7828571428571428
5 0.6742857142857143
6 0.7257142857142858
7 0.64
8 0.7885714285714286
9 0.7485714285714286
10 0.8171428571428572
11 0.6742857142857143
12 0.7428571428571429
13 0.7657142857142857
14 0.6457142857142857
15 0.7542857142857143
16 0.7371428571428571
17 0.7942857142857143
18 0.7314285714285714

In [29]:
def rf(nestimator, traindata, testdata, accuracylist): 
    total_sum=0
    for i in range (19): 
        rf = RandomForestClassifier(n_estimators=nestimator, max_depth = 10, random_state=42)
        smited=rf.fit (traindata[i],train_activity[i])
        smited_pred = rf.predict(testdata)

        accuracy = accuracy_score(test_activity, smited_pred)
        accuracylist.append(accuracy)
        total_sum += accuracy
        
    average_accuracy = total_sum /len(traindata)
    return print(average_accuracy)
        
accuracysmited5 = []
accuracysmited10 = []
accuracysmited15= []

rf(5,train_emb,test_emb[0],accuracysmited5)
rf(10,train_emb,test_emb[0],accuracysmited10)
rf(15,train_emb,test_emb[0],accuracysmited15)

0.7374436090225563
0.8063157894736844
0.7903759398496241

In [30]:
accuracyrdkit5 = []
accuracyrdkit10 = []
accuracyrdkit15= []

rf(5,train_rdkit,test_rdkit,accuracyrdkit5)
rf(10,train_rdkit,test_rdkit,accuracyrdkit10)
rf(15,train_rdkit,test_rdkit,accuracyrdkit15)

0.7726315789473684
0.8126315789473686
0.7969924812030076

In [34]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

clf = make_pipeline(
    StandardScaler(),
    MLPClassifier(random_state=1, max_iter=1000)
)

clf.fit(train_emb[1], train_activity[1])

accuracy = clf.score(test_emb[1], test_activity)
print(accuracy)

0.8285714285714286

In [37]:
X_train_full = np.array(train_rdkit[1])
X_test_full = np.array(test_rdkit)

mask = ~np.isnan(X_train_full).any(axis=0)

X_train = X_train_full[:, mask]
X_test = X_test_full[:, mask]

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

clf = make_pipeline(
    StandardScaler(),
    MLPClassifier(random_state=1, max_iter=1000)
)

clf.fit(X_train, train_activity[1])

accuracy = clf.score(X_test, test_activity)
print(accuracy)

0.76